### ISSUE TITLE
Terms xls download contains HTML in the description

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#237]
The description of the terms downloaded to excel has HTML in it.  This could be confusing for many people and also makes the data hard to use.

![image](https://cloud.githubusercontent.com/assets/19391188/15684535/84476fc6-2735-11e6-949a-cef6beecd70c.png)

**Comment by RyanSnodgrass** [comment]
This is expected behavior as much of the content is in bullet lists, tables, or other things that will appear completely garbled if the html elements are removed. There are [several (albeit rather technical)](http://stackoverflow.com/questions/9999713/html-text-with-tags-to-formatted-text-in-an-excel-cell) ways to get excel to display html in the cell.

The only use for the Excel download is for Augie. If we really don't like this feature, we can limit it's use to just admins.

Recommending this issue be closed.

**Comment by RyanSnodgrass** [comment]
Closing. If we get complaints, we can reopen
